name: build-check

on:
  push:
    branches: [GMS-05-add-build-check]
  pull_request:
    branches: [GMS-05-add-build-check]

jobs:
  avoid-redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Installing dependencies
        run: pnpm install

  prettier:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    environment: develop
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Installing dependencies
        run: pnpm install
      - name: Prisma Generate
        run: pnpm prisma generate
      - name: lint
        run: pnpm prettier

  lint:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    environment: develop
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Installing dependencies
        run: pnpm install
      - name: Prisma Generate
        run: pnpm prisma generate
      - name: lint
        run: pnpm lint

  verify-build:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Installing dependencies
        run: pnpm install
      - name: Prisma Generate
        run: pnpm prisma generate
      - name: Creating build
        run: pnpm build

